# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST  https://localhost:7431/search
content-type: application/json

{
  "query": "What is AI transparency?"
}

###

POST  https://localhost:7431/ask
content-type: application/json

{
  "query": "What is AI transparency?"
}
