@CardTrackerWebApi_HostAddress = http://localhost:5197

### Get all decks (Anonymous)
GET {{CardTrackerWebApi_HostAddress}}/decks/
Accept: application/json

### Login
POST {{CardTrackerWebApi_HostAddress}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "PacktBooks"
}

> {% client.global.set("auth_token", response.body.token); %}

### Get all users (requires admin)
GET {{CardTrackerWebApi_HostAddress}}/users
Authorization: Bearer {{auth_token}}

### Create user (Requires admin)
POST {{CardTrackerWebApi_HostAddress}}/users
Content-Type: application/json

{
  "username": "testuser",
  "password": "PacktBooks",
  "isAdmin": true
}

### Get User (requires admin)
GET {{CardTrackerWebApi_HostAddress}}/users/testuser
Authorization: Bearer {{auth_token}}
