@CardTrackerWebApi_HostAddress = http://localhost:5197

GET {{CardTrackerWebApi_HostAddress}}/decks/
Accept: application/json

###

GET {{CardTrackerWebApi_HostAddress}}/users
Accept: application/json
X-API-KEY: REPLACE_IN_PRODUCTION

###

POST {{CardTrackerWebApi_HostAddress}}/users
Content-Type: application/json
X-API-KEY: REPLACE_IN_PRODUCTION

{
  "username": "meland"
}