@ChatApi_HostAddress = http://localhost:5189

POST {{ChatApi_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
  "Messages": [
    {"Role": "assistant", "Message": "Hello there. How are you?"},
    {"Role": "user", "Message": "I'm fine. How are you today?"}
  ]
}

###

POST {{ChatApi_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
  "Messages": [
    {"Role": "user", "Message": "Roll two six-sided dice and tell me the result."}
  ]
}
